### ISSUE TITLE
Empty search value

### ISSUE THREAD

**Issue by zloirock** [es-shims/String.prototype.replaceAll#1]
[The example from the proposals repo](https://github.com/tc39/proposal-string-replaceall#what-happens-if-searchvalue-is-the-empty-string) causes infinity loop:
```js
'xxx'.replaceAll('', '_');
```

**Comment by ljharb** [comment]
Thanks, good catch. This looks like an artifact of https://github.com/tc39/proposal-string-replaceall/issues/32.

This actually might be a bug in the spec text - https://github.com/zloirock/core-js/blob/081785956a2efe65f1c381ee08b757741d5c0a7b/packages/core-js/modules/esnext.string.replace-all.js#L36, for example, seems like a workaround for that bug.
