### ISSUE TITLE
Failed to load config "@ljharb" to extend from

### ISSUE THREAD

**Issue by deadmann** [es-shims/String.prototype.replaceAll#13]
Since I intalled this dependency we are receiving tons of error regarding the `Failed to load config "@ljharb" to extend from`...
![image](https://user-images.githubusercontent.com/1919241/209777942-3ae0849d-c73e-40c5-962d-a48e5df4d811.png)
![image](https://user-images.githubusercontent.com/1919241/209777970-105cb081-7ad0-46d8-8afe-d13e0d2720d5.png)
![image](https://user-images.githubusercontent.com/1919241/209777995-8eec5cfb-3619-42fa-9894-166ff45cf46a.png)
![image](https://user-images.githubusercontent.com/1919241/209778022-4c365986-b9c0-41bd-8da0-adf70d509608.png)
![image](https://user-images.githubusercontent.com/1919241/209778055-fadb2953-9701-463a-8081-e979987ebe9f.png)
![image](https://user-images.githubusercontent.com/1919241/209778081-7baab192-9971-40bc-a553-4f20a4f71a53.png)

My company uses: Micro-Frontend, Vue, Web-pack...
I tried to use eslint ignore file, to ignore node modules but it didn't worked...

**Comment by ljharb** [comment]
This happens because you are linting files inside node_modules, which you shouldn't ever be. If you have trouble ignoring these, file an issue on eslint (but if you're in a monorepo you might need to ignore `**/node_modules/**` as well).

**Comment by deadmann** [comment]
yeah, they said it in other places too, but that didn't work for me...
I used `node_modules`, `node_modules/**`, and `**/node_modules/**`, none worked

in eslint ignore file

**Comment by ljharb** [comment]
Then file an issue on eslint - it's not a problem with this package.
