### ISSUE TITLE
Library cannot be tested on standard npm runkit

### ISSUE THREAD

**Issue by char0n** [es-shims/String.prototype.replaceAll#2]
@ljharb nice! Unfortunately I haven't been able to test https://npmjs.com/string.prototype.replaceall in runkit: https://npm.runkit.com/string.prototype.replaceall. It's getting `Error: Cannot find module 'define-properties'` error.

**Comment by ljharb** [comment]
Turns out this is a missing top-level dep; it works locally because npm hoists it to the top.

**Comment by ljharb** [comment]
I'll publish a patch shortly.

**Comment by ljharb** [comment]
v1.0.2 is released; runkit works now.
